version: '3.3'
services:
  snappy-db:
    image: 'mdillon/postgis:10-alpine'
    container_name: snappy-auth.db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=click123 # Corrected the variable name
      - POSTGRES_DB=snappy

  # snappy-server:
  #   build:
  #     context: .
  #   container_name: snappy-auth-server
  #   ports:
  #     - '3000:3000'
  #   restart: always
  #   depends_on:
  #     - snappy-db
  #   command: ["npm", "run","start:dev"]
  #   env_file:
  #     - ./.env
